version: '3.7'


services:
  distributor:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8004"
    ports:
      - 8004:8004
    networks:
      - distr_net
    volumes:
      - ./:/web
    restart: always

  node1:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"
    ports:
      - 8001:8001
    networks:
      - distr_net
    volumes:
      - ./:/web
    restart: always

  node2:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8002"
    ports:
      - 8002:8002
    networks:
      - distr_net
    volumes:
      - ./:/web
    restart: always

  node3:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8003"
    ports:
      - 8003:8003
    networks:
      - distr_net
    volumes:
      - ./:/web
    restart: always

networks:
  distr_net:
    external: true


