# Generated by Django 4.1 on 2022-10-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_port', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
